mport random
def guess():
    computer=random.choice(range(1,51))

    print("===============================================================================================")
    print("|                                                                                             |")
    print("|                                  Welcome to the Guessing Game!                              |")
    print("|                                                                                             |")
    print("===============================================================================================")
    print("Instructions:")
    print("""1.System generates a random number between 1 to 50.
          
2. Player guesses the number and has 6 lives.
          
3. System gives hints: Too High / Too Low and lives remaining.
          
4.Attempts are counted for each guess and if guess is wrong, lives decreases by 1.
          
5.Game ends when the correct number is guessed.
          
6.The leader board is updated with the player's name and attempts taken to guess the number.""")
    lives=6
    attempts=0
    name=input("Enter your name to start the game:")
    while(lives>0):
        chose=int(input("choose a number between 1 to 50:"))
        print(f"you have{lives} remaining! ")
        attempts+=1
        if(computer==chose and 1 <= chose <= 50):
            print(f"Congratulations! You guessed the number {computer} in {attempts} attempts!＾▽＾")
            with open("guess_leaderboard.txt","a") as f:
                f.write(f"{name}:{attempts}\n")
            break
        elif computer!=chose and 1 <= chose <= 50:
            print("oh no! wrong guess ︶︹︺ ")
            lives-=1
            if computer>chose and lives>0:
                print("please enter a higher number")
            elif computer<chose and lives>0:
                print("please enter a lower number")
            
        else:
            print("please enter a number between 1 to 50")
        
    if(lives==0):
        print("Oh! You ran out of lives.Better luck next time.•‿•")
        attempts="lost the game"
        with open("guess_leaderboard.txt","a") as f:
                f.write(f"{name}:{attempts}\n")
    highscore = 7

    with open("guess_leaderboard.txt","r") as f:
        for line in f:
            name,score = line.strip().split(":")

            if score != "lost the game":
                score = int(score)
                if score < highscore:
                    highscore = score

    print("Highscore is:",highscore)
    print("The number generated by computer was",computer)
    
    print("=================================================LEADERBOARD================================================")
    with open("guess_leaderboard.txt","r") as f:
        for line in f:
            name,score = line.strip().split(":")

            if score != "lost the game":
                score = int(score)
                if score == highscore:
                    print(f"{name}:{score} attempts - highscore")
                else:
                    print(f"{name}:{score} attempts")
            else:
                print(f"{name}:lost the game")
                
guess()

    
        




    